"""Add post_details and tags relationships

Revision ID: 06f9dd3c6b7b
Revises: 2892821fc954
Create Date: 2024-12-11 18:10:03.327766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f9dd3c6b7b'
down_revision: Union[str, None] = '2892821fc954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
