"""Remove unique constraint from Tag.name

Revision ID: 16a54ca6895d
Revises: 06f9dd3c6b7b
Create Date: 2024-12-12 11:47:49.147284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a54ca6895d'
down_revision: Union[str, None] = '06f9dd3c6b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
