"""Fix one-to-many relationship between FeatureRelease and Tag

Revision ID: 2892821fc954
Revises: cb72a2e9ceba
Create Date: 2024-12-11 17:12:18.534480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2892821fc954'
down_revision: Union[str, None] = 'cb72a2e9ceba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
