"""Added UUID column

Revision ID: a29ac93389ba
Revises: 16a54ca6895d
Create Date: 2024-12-12 15:38:12.019991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29ac93389ba'
down_revision: Union[str, None] = '16a54ca6895d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_releases', sa.Column('uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feature_releases_uuid'), 'feature_releases', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_releases_uuid'), table_name='feature_releases')
    op.drop_column('feature_releases', 'uuid')
    # ### end Alembic commands ###
