"""Added UUID column

Revision ID: c6cecfcb26c9
Revises: a29ac93389ba
Create Date: 2024-12-12 17:55:47.651792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cecfcb26c9'
down_revision: Union[str, None] = 'a29ac93389ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_releases_uuid', table_name='feature_releases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_feature_releases_uuid', 'feature_releases', ['uuid'], unique=False)
    # ### end Alembic commands ###
