"""Initial migration

Revision ID: cb72a2e9ceba
Revises: fd0df73108e3
Create Date: 2024-12-11 16:34:27.745639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb72a2e9ceba'
down_revision: Union[str, None] = 'fd0df73108e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_ambassador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('cv', sa.LargeBinary(), nullable=True),
    sa.Column('want_to_be', sa.String(), nullable=True),
    sa.Column('in_any_club', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('linkdin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_ambassador_email_address'), 'campus_ambassador', ['email_address'], unique=True)
    op.create_index(op.f('ix_campus_ambassador_id'), 'campus_ambassador', ['id'], unique=False)
    op.create_index(op.f('ix_campus_ambassador_name'), 'campus_ambassador', ['name'], unique=False)
    op.create_table('feature_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_version', sa.String(), nullable=True),
    sa.Column('post_image_url', sa.String(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_releases_id'), 'feature_releases', ['id'], unique=False)
    op.create_index(op.f('ix_feature_releases_title'), 'feature_releases', ['title'], unique=False)
    op.create_table('post_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text_area', sa.Text(), nullable=True),
    sa.Column('feature_release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_release_id'], ['feature_releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_details_id'), 'post_details', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('feature_release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_release_id'], ['feature_releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_post_details_id'), table_name='post_details')
    op.drop_table('post_details')
    op.drop_index(op.f('ix_feature_releases_title'), table_name='feature_releases')
    op.drop_index(op.f('ix_feature_releases_id'), table_name='feature_releases')
    op.drop_table('feature_releases')
    op.drop_index(op.f('ix_campus_ambassador_name'), table_name='campus_ambassador')
    op.drop_index(op.f('ix_campus_ambassador_id'), table_name='campus_ambassador')
    op.drop_index(op.f('ix_campus_ambassador_email_address'), table_name='campus_ambassador')
    op.drop_table('campus_ambassador')
    # ### end Alembic commands ###
